name: ohw-core
main: net.ohw.menus.CompassMenuPlugin
version: 1.0.2
# api-version field introduced in 1.13+, remove for 1.8.9 compatibility
commands:
  menu:
    description: menu
    usage: /menu
    permission: ohw.menu.use
    permission-message: 您沒有權限使用此指令
  nick:
    description: nick
    permission: ohw.nick.premium
    permission-message: §c您目前的 Rank 等級不足以使用此指令！

permissions:
  ohw.nick.premium:
    description: 允許使用 /nick 指令 (MVP++ 專屬)
    default: op