name: ohw-core
main: net.ohw.menus.CompassMenuPlugin
version: 1.0.2
authors:
  - InyTw
  - ohw Admin Team
# api-version field introduced in 1.13+, remove for 1.8.9 compatibility
commands:
  menu:
    description: menu
    usage: /menu
    permission: ohw.menu.use
    permission-message: 您沒有權限使用此指令